joint_limits:
  right_shoulder_pitch_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  right_shoulder_roll_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  right_shoulder_yaw_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  right_elbow_pitch_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  right_wrist_yaw_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  right_wrist_pitch_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  right_wrist_roll_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  right_index_finger_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  right_middle_finger_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  right_thumb_yaw_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true
  right_thumb_pitch_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    angle_wraparound: true