multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: torso_base_link
    child_frame_id: torso_base_link
groups:
  - name: mk2_right_arm
    base_link: torso_roll_link
    tip_link: right_wrist_roll_link
  - name: right_end_effector
    joints:
      - right_index_finger_joint
      - right_middle_finger_joint
      - right_thumb_yaw_joint
      - right_thumb_pitch_joint
default_collision_operations:
  - object1: torso_base_link
    object2: torso_yaw_link
    operation: disable  # Adjacent in collision
  -
    object1: torso_yaw_link
    object2: torso_pitch_link
    operation: disable  # Adjacent in collision
  -
    object1: torso_pitch_link
    object2: torso_roll_link
    operation: disable  # Adjacent in collision
  -
    object1: torso_roll_link
    object2: right_shoulder_pitch_link
    operation: disable  # Adjacent in collision
  -
    object1: right_shoulder_pitch_link
    object2: right_shoulder_roll_link
    operation: disable  # Adjacent in collision
  -
    object1: right_shoulder_roll_link
    object2: right_shoulder_yaw_link
    operation: disable  # Adjacent in collision
  -
    object1: right_shoulder_yaw_link
    object2: right_elbow_pitch_link
    operation: disable  # Adjacent in collision
  -
    object1: right_elbow_pitch_link
    object2: right_wrist_yaw_link
    operation: disable  # Adjacent in collision
  -
    object1: right_wrist_yaw_link
    object2: right_wrist_pitch_link
    operation: disable  # Adjacent in collision
  -
    object1: right_wrist_pitch_link
    object2: right_wrist_roll_link
    operation: disable  # Adjacent in collision
  -
    object1: right_wrist_roll_link
    object2: right_palm_link
    operation: disable  # Adjacent in collision
  -
    object1: right_palm_link
    object2: right_index_finger_link
    operation: disable  # Adjacent in collision
  -
    object1: right_palm_link
    object2: right_middle_finger_link
    operation: disable  # Adjacent in collision
  -
    object1: right_palm_link
    object2: right_thumb_yaw_link
    operation: disable  # Adjacent in collision
  -
    object1: right_thumb_yaw_link
    object2: right_thumb_pitch_link
    operation: disable  # Adjacent in collision
  -
    object1: right_palm_link
    object2: right_thumb_pitch_link
    operation: disable  # Often in collision
  -
    object1: right_wrist_roll_link
    object2: right_wrist_yaw_link
    operation: disable  # Often in collision
  -
    object1: torso_roll_link
    object2: torso_yaw_link
    operation: disable  # Often in collision
  -
    object1: right_elbow_pitch_link
    object2: right_shoulder_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_elbow_pitch_link
    object2: right_shoulder_roll_link
    operation: disable  # Never in collision
  -
    object1: right_elbow_pitch_link
    object2: right_wrist_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_elbow_pitch_link
    object2: right_wrist_roll_link
    operation: disable  # Never in collision
  -
    object1: right_index_finger_link
    object2: right_middle_finger_link
    operation: disable  # Never in collision
  -
    object1: right_index_finger_link
    object2: right_wrist_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_index_finger_link
    object2: right_wrist_roll_link
    operation: disable  # Never in collision
  -
    object1: right_middle_finger_link
    object2: right_wrist_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_middle_finger_link
    object2: right_wrist_roll_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_pitch_link
    object2: torso_base_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_pitch_link
    object2: torso_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_pitch_link
    object2: torso_yaw_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_roll_link
    object2: torso_base_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_roll_link
    object2: torso_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_roll_link
    object2: torso_roll_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_roll_link
    object2: torso_yaw_link
    operation: disable  # Never in collision
  -
    object1: right_thumb_yaw_link
    object2: right_wrist_roll_link
    operation: disable  # Never in collision