/* Auto-generated by genmsg_cpp for file /home/dasl/rosbuild_ws/dasl-ros-pkg/dasl_mocap/msg/RigidBody.msg */
#ifndef DASL_MOCAP_MESSAGE_RIGIDBODY_H
#define DASL_MOCAP_MESSAGE_RIGIDBODY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace dasl_mocap
{
template <class ContainerAllocator>
struct RigidBody_ {
  typedef RigidBody_<ContainerAllocator> Type;

  RigidBody_()
  : X(0.0)
  , Y(0.0)
  , Z(0.0)
  {
  }

  RigidBody_(const ContainerAllocator& _alloc)
  : X(0.0)
  , Y(0.0)
  , Z(0.0)
  {
  }

  typedef float _X_type;
  float X;

  typedef float _Y_type;
  float Y;

  typedef float _Z_type;
  float Z;


  typedef boost::shared_ptr< ::dasl_mocap::RigidBody_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dasl_mocap::RigidBody_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RigidBody
typedef  ::dasl_mocap::RigidBody_<std::allocator<void> > RigidBody;

typedef boost::shared_ptr< ::dasl_mocap::RigidBody> RigidBodyPtr;
typedef boost::shared_ptr< ::dasl_mocap::RigidBody const> RigidBodyConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::dasl_mocap::RigidBody_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::dasl_mocap::RigidBody_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace dasl_mocap

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dasl_mocap::RigidBody_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dasl_mocap::RigidBody_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dasl_mocap::RigidBody_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a1dfb8f61d81d8e9fe291bc0d86a2f48";
  }

  static const char* value(const  ::dasl_mocap::RigidBody_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa1dfb8f61d81d8e9ULL;
  static const uint64_t static_value2 = 0xfe291bc0d86a2f48ULL;
};

template<class ContainerAllocator>
struct DataType< ::dasl_mocap::RigidBody_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dasl_mocap/RigidBody";
  }

  static const char* value(const  ::dasl_mocap::RigidBody_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dasl_mocap::RigidBody_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 X\n\
float32 Y\n\
float32 Z\n\
\n\
";
  }

  static const char* value(const  ::dasl_mocap::RigidBody_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::dasl_mocap::RigidBody_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dasl_mocap::RigidBody_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.X);
    stream.next(m.Y);
    stream.next(m.Z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RigidBody_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dasl_mocap::RigidBody_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::dasl_mocap::RigidBody_<ContainerAllocator> & v) 
  {
    s << indent << "X: ";
    Printer<float>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<float>::stream(s, indent + "  ", v.Y);
    s << indent << "Z: ";
    Printer<float>::stream(s, indent + "  ", v.Z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DASL_MOCAP_MESSAGE_RIGIDBODY_H

