/* Auto-generated by genmsg_cpp for file /home/dasl/rosbuild_ws/dasl-ros-pkg/dasl_mocap/msg/Vector3F.msg */
#ifndef DASL_MOCAP_MESSAGE_VECTOR3F_H
#define DASL_MOCAP_MESSAGE_VECTOR3F_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace dasl_mocap
{
template <class ContainerAllocator>
struct Vector3F_ {
  typedef Vector3F_<ContainerAllocator> Type;

  Vector3F_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  Vector3F_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;


  typedef boost::shared_ptr< ::dasl_mocap::Vector3F_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dasl_mocap::Vector3F_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Vector3F
typedef  ::dasl_mocap::Vector3F_<std::allocator<void> > Vector3F;

typedef boost::shared_ptr< ::dasl_mocap::Vector3F> Vector3FPtr;
typedef boost::shared_ptr< ::dasl_mocap::Vector3F const> Vector3FConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::dasl_mocap::Vector3F_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::dasl_mocap::Vector3F_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace dasl_mocap

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dasl_mocap::Vector3F_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dasl_mocap::Vector3F_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dasl_mocap::Vector3F_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const  ::dasl_mocap::Vector3F_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::dasl_mocap::Vector3F_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dasl_mocap/Vector3F";
  }

  static const char* value(const  ::dasl_mocap::Vector3F_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dasl_mocap::Vector3F_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
\n\
";
  }

  static const char* value(const  ::dasl_mocap::Vector3F_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::dasl_mocap::Vector3F_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dasl_mocap::Vector3F_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Vector3F_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dasl_mocap::Vector3F_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::dasl_mocap::Vector3F_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DASL_MOCAP_MESSAGE_VECTOR3F_H

