/* Auto-generated by genmsg_cpp for file /home/dasl/rosbuild_ws/dasl-ros-pkg/dasl_mocap/msg/Velocity.msg */
#ifndef DASL_MOCAP_MESSAGE_VELOCITY_H
#define DASL_MOCAP_MESSAGE_VELOCITY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace dasl_mocap
{
template <class ContainerAllocator>
struct Velocity_ {
  typedef Velocity_<ContainerAllocator> Type;

  Velocity_()
  : linear(0.0)
  , angular(0.0)
  {
  }

  Velocity_(const ContainerAllocator& _alloc)
  : linear(0.0)
  , angular(0.0)
  {
  }

  typedef float _linear_type;
  float linear;

  typedef float _angular_type;
  float angular;


  typedef boost::shared_ptr< ::dasl_mocap::Velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dasl_mocap::Velocity_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Velocity
typedef  ::dasl_mocap::Velocity_<std::allocator<void> > Velocity;

typedef boost::shared_ptr< ::dasl_mocap::Velocity> VelocityPtr;
typedef boost::shared_ptr< ::dasl_mocap::Velocity const> VelocityConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::dasl_mocap::Velocity_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::dasl_mocap::Velocity_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace dasl_mocap

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dasl_mocap::Velocity_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dasl_mocap::Velocity_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dasl_mocap::Velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9d5c2dcd348ac8f76ce2a4307bd63a13";
  }

  static const char* value(const  ::dasl_mocap::Velocity_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9d5c2dcd348ac8f7ULL;
  static const uint64_t static_value2 = 0x6ce2a4307bd63a13ULL;
};

template<class ContainerAllocator>
struct DataType< ::dasl_mocap::Velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dasl_mocap/Velocity";
  }

  static const char* value(const  ::dasl_mocap::Velocity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dasl_mocap::Velocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 linear\n\
float32 angular\n\
\n\
";
  }

  static const char* value(const  ::dasl_mocap::Velocity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::dasl_mocap::Velocity_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dasl_mocap::Velocity_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.linear);
    stream.next(m.angular);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Velocity_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dasl_mocap::Velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::dasl_mocap::Velocity_<ContainerAllocator> & v) 
  {
    s << indent << "linear: ";
    Printer<float>::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DASL_MOCAP_MESSAGE_VELOCITY_H

