controller_list:
  - name: fake_manipulator_controller
    joints:
      - torso_yaw_joint
      - torso_pitch_joint
      - torso_roll_joint
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7