multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: torso_roll_link
    child_frame_id: torso_roll_link
groups:
  - name: arm
    base_link: torso_roll_link
    tip_link: right_wrist_roll_link
  - name: manipulator
    base_link: torso_roll_link
    tip_link: right_wrist_roll_link
default_collision_operations:
  - object1: torso_roll_link
    object2: right_shoulder_pitch_link
    operation: disable  # Adjacent in collision
  -
    object1: right_shoulder_pitch_link
    object2: right_shoulder_roll_link
    operation: disable  # Adjacent in collision
  -
    object1: right_shoulder_roll_link
    object2: right_shoulder_yaw_link
    operation: disable  # Adjacent in collision
  -
    object1: right_shoulder_yaw_link
    object2: right_elbow_pitch_link
    operation: disable  # Adjacent in collision
  -
    object1: right_elbow_pitch_link
    object2: right_wrist_yaw_link
    operation: disable  # Adjacent in collision
  -
    object1: right_wrist_yaw_link
    object2: right_wrist_pitch_link
    operation: disable  # Adjacent in collision
  -
    object1: right_wrist_pitch_link
    object2: right_wrist_roll_link
    operation: disable  # Adjacent in collision
  -
    object1: right_elbow_pitch_link
    object2: right_shoulder_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_elbow_pitch_link
    object2: right_shoulder_roll_link
    operation: disable  # Never in collision
  -
    object1: right_elbow_pitch_link
    object2: right_wrist_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_elbow_pitch_link
    object2: right_wrist_roll_link
    operation: disable  # Never in collision
  -
    object1: right_elbow_pitch_link
    object2: torso_roll_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_pitch_link
    object2: right_shoulder_yaw_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_pitch_link
    object2: right_wrist_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_pitch_link
    object2: right_wrist_roll_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_pitch_link
    object2: right_wrist_yaw_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_roll_link
    object2: right_wrist_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_roll_link
    object2: right_wrist_roll_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_roll_link
    object2: right_wrist_yaw_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_roll_link
    object2: torso_roll_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_yaw_link
    object2: right_wrist_pitch_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_yaw_link
    object2: right_wrist_roll_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_yaw_link
    object2: right_wrist_yaw_link
    operation: disable  # Never in collision
  -
    object1: right_shoulder_yaw_link
    object2: torso_roll_link
    operation: disable  # Never in collision