"""autogenerated by genpy from mocap/pc2quadcopter.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mocap.msg

class pc2quadcopter(genpy.Message):
  _md5sum = "eb0ec6ee65ae149f4b3914a1dece2323"
  _type = "mocap/pc2quadcopter"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Vector3F position
Vector3F speed
Vector3F orientation
float32 roll
float32 pitch
float32 yaw
float32 thrust

================================================================================
MSG: mocap/Vector3F
float32 x
float32 y
float32 z

"""
  __slots__ = ['position','speed','orientation','roll','pitch','yaw','thrust']
  _slot_types = ['mocap/Vector3F','mocap/Vector3F','mocap/Vector3F','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,speed,orientation,roll,pitch,yaw,thrust

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pc2quadcopter, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = mocap.msg.Vector3F()
      if self.speed is None:
        self.speed = mocap.msg.Vector3F()
      if self.orientation is None:
        self.orientation = mocap.msg.Vector3F()
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.thrust is None:
        self.thrust = 0.
    else:
      self.position = mocap.msg.Vector3F()
      self.speed = mocap.msg.Vector3F()
      self.orientation = mocap.msg.Vector3F()
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.thrust = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_13f.pack(_x.position.x, _x.position.y, _x.position.z, _x.speed.x, _x.speed.y, _x.speed.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.roll, _x.pitch, _x.yaw, _x.thrust))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.position is None:
        self.position = mocap.msg.Vector3F()
      if self.speed is None:
        self.speed = mocap.msg.Vector3F()
      if self.orientation is None:
        self.orientation = mocap.msg.Vector3F()
      end = 0
      _x = self
      start = end
      end += 52
      (_x.position.x, _x.position.y, _x.position.z, _x.speed.x, _x.speed.y, _x.speed.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.roll, _x.pitch, _x.yaw, _x.thrust,) = _struct_13f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_13f.pack(_x.position.x, _x.position.y, _x.position.z, _x.speed.x, _x.speed.y, _x.speed.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.roll, _x.pitch, _x.yaw, _x.thrust))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.position is None:
        self.position = mocap.msg.Vector3F()
      if self.speed is None:
        self.speed = mocap.msg.Vector3F()
      if self.orientation is None:
        self.orientation = mocap.msg.Vector3F()
      end = 0
      _x = self
      start = end
      end += 52
      (_x.position.x, _x.position.y, _x.position.z, _x.speed.x, _x.speed.y, _x.speed.z, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.roll, _x.pitch, _x.yaw, _x.thrust,) = _struct_13f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_13f = struct.Struct("<13f")
