# YAML Configuration file that specifies additional properties about each joint by creating an array of structs

joints:

  - name: joint_1
    channel: 1 
    home: 0.0

  - name: joint_2
    channel: 2
    home: 0.0

  - name: joint_3
    channel: 3
    home: 0.0

  - name: joint_4
    channel: 4
    home: 0.0

  - name: joint_5
    channel: 5
    home: 0.0

  - name: joint_6
    channel: 6
    home: 0.0

  - name: joint_7
    channel: 7
    home: 0.0
