joint_limits:
  joint_4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 0.4
  joint_1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 0.4
  joint_6:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: true
    max_acceleration: 0.4